{{-- 
    Theme Engine CSS Variables
    
    Injected into all layouts (portal, public, auth) to provide
    dynamic CSS variables resolved from the active tenant theme.
    
    Variables are generated by App\Services\ThemeCssGenerator
    and cached by App\Services\ThemeCacheService.
--}}

{{-- Dynamic theme CSS variables --}}
<style id="theme-engine-variables">
    {!! $themeCss ?? '' !!}
</style>

{{-- Tenant custom CSS (sanitized) --}}
@if(!empty($themeCustomCss))
<style id="theme-engine-custom">
    {!! $themeCustomCss !!}
</style>
@endif

{{-- Font preloading --}}
@php
    $fontPrimary = $theme->font_primary ?? config('theme.defaults.font_primary', 'Inter');
    $fontSecondary = $theme->font_secondary ?? config('theme.defaults.font_secondary', 'Poppins');
@endphp
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
